# Generated by Django 4.2.7 on 2026-03-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="acessousuario",
            new_name="core_acesso_usuario_4e2594_idx",
            old_name="core_acesso_usuario_9b9817_idx",
        ),
        migrations.RenameIndex(
            model_name="acessousuario",
            new_name="core_acesso_contabi_9bac9a_idx",
            old_name="core_acesso_contabi_7c94f7_idx",
        ),
        migrations.RenameIndex(
            model_name="acessousuario",
            new_name="core_acesso_imobili_c9d6f5_idx",
            old_name="core_acesso_imobili_df4b56_idx",
        ),
        migrations.RenameIndex(
            model_name="comprador",
            new_name="core_compra_tipo_pe_57af42_idx",
            old_name="core_compra_tipo_pe_f08b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="comprador",
            new_name="core_compra_cpf_1f145e_idx",
            old_name="core_compra_cpf_eeffd1_idx",
        ),
        migrations.RenameIndex(
            model_name="comprador",
            new_name="core_compra_cnpj_442f54_idx",
            old_name="core_compra_cnpj_7c3db1_idx",
        ),
        migrations.RenameIndex(
            model_name="imovel",
            new_name="core_imovel_disponi_22f62a_idx",
            old_name="core_imovel_disponi_57a3c5_idx",
        ),
        migrations.RenameIndex(
            model_name="imovel",
            new_name="core_imovel_loteame_4e69ea_idx",
            old_name="core_imovel_loteame_e88d07_idx",
        ),
    ]
