# Generated by Django 4.2.7 on 2026-04-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reajuste_desconto_periodo_referencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="lote",
            field=models.CharField(
                blank=True,
                help_text="Número do lote (ex: 13, 15A)",
                max_length=20,
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="imovel",
            name="quadra",
            field=models.CharField(
                blank=True,
                help_text="Identificação da quadra/bloco (ex: A, B, 01)",
                max_length=20,
                verbose_name="Quadra",
            ),
        ),
    ]
