# Generated by Django 4.2.7 on 2026-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_imobiliaria_tipo_pessoa_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="byte_idt",
            field=models.CharField(
                blank=True,
                help_text='Byte de identificação. Obrigatório para Sicredi (1 dígito, geralmente "2")',
                max_length=1,
                verbose_name="Byte IDT (Sicredi)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="codigo_beneficiario",
            field=models.CharField(
                blank=True,
                help_text="Código do beneficiário. Obrigatório para Caixa Econômica (geralmente igual ao convênio)",
                max_length=20,
                verbose_name="Código Beneficiário (Caixa)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="emissao",
            field=models.CharField(
                blank=True,
                help_text='Tipo de emissão. Obrigatório para Caixa Econômica (1 dígito, geralmente "4")',
                max_length=1,
                verbose_name="Emissão (Caixa)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="posto",
            field=models.CharField(
                blank=True,
                help_text="Código do posto. Obrigatório para Sicredi (2 dígitos)",
                max_length=2,
                verbose_name="Posto (Sicredi)",
            ),
        ),
        migrations.AlterField(
            model_name="imobiliaria",
            name="cnpj",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório para PJ. Suporta formato alfanumérico (preparado para 2026)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="imobiliaria",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório para vendedor Pessoa Física (formato XXX.XXX.XXX-XX)",
                max_length=14,
                null=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="imobiliaria",
            name="nome",
            field=models.CharField(
                help_text="Razão Social para PJ ou Nome Completo para PF",
                max_length=200,
                verbose_name="Nome / Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="imobiliaria",
            name="razao_social",
            field=models.CharField(
                blank=True,
                help_text="Razão social ou nome fantasia (opcional para PF)",
                max_length=200,
                verbose_name="Razão Social / Nome Fantasia",
            ),
        ),
        migrations.AlterField(
            model_name="imobiliaria",
            name="tipo_pessoa",
            field=models.CharField(
                choices=[("PJ", "Pessoa Jurídica"), ("PF", "Pessoa Física")],
                default="PJ",
                help_text="PJ = Empresa/Imobiliária · PF = Vendedor Pessoa Física",
                max_length=2,
                verbose_name="Tipo de Pessoa",
            ),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="identificacao",
            field=models.CharField(
                help_text="Identificação do imóvel (ex: Apt 301, Quadra A Lote 13, Sala 5, Quarto 214)",
                max_length=100,
                verbose_name="Identificação",
            ),
        ),
    ]
