# Generated by Django 4.2.7 on 2026-04-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_bank_specific_fields_to_conta_bancaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="imobiliaria",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="PNG ou JPG, máx. 2 MB. Recomendado: fundo transparente.",
                null=True,
                upload_to="imobiliarias/logos/",
                verbose_name="Logo",
            ),
        ),
    ]
