# Generated by Django 4.2.7 on 2026-04-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_logo_imobiliaria"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerticePoligono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(verbose_name="Ordem")),
                (
                    "latitude",
                    models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Longitude"),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertices",
                        to="core.imovel",
                        verbose_name="Imóvel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vértice de Polígono",
                "verbose_name_plural": "Vértices de Polígonos",
                "ordering": ["imovel", "ordem"],
                "unique_together": {("imovel", "ordem")},
            },
        ),
    ]
