# Generated by Django 4.2.7 on 2026-04-09 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_vertice_poligono"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantaBaixaLoteamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "loteamento",
                    models.CharField(
                        help_text="Deve corresponder exatamente ao campo Loteamento dos imóveis.",
                        max_length=200,
                        verbose_name="Loteamento/Empreendimento",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="plantas_baixas/",
                        verbose_name="Planta Baixa (arquivo)",
                    ),
                ),
                (
                    "imagem_db",
                    models.BinaryField(
                        blank=True,
                        help_text="Cópia da imagem em banco de dados — persiste em storage efêmero.",
                        null=True,
                        verbose_name="Planta Baixa (banco de dados)",
                    ),
                ),
                (
                    "imagem_content_type",
                    models.CharField(
                        default="image/png", max_length=50, verbose_name="Content-Type da imagem"
                    ),
                ),
                (
                    "lat_sw",
                    models.DecimalField(
                        decimal_places=7, max_digits=12, verbose_name="Latitude SW (sul)"
                    ),
                ),
                (
                    "lng_sw",
                    models.DecimalField(
                        decimal_places=7, max_digits=12, verbose_name="Longitude SW (oeste)"
                    ),
                ),
                (
                    "lat_ne",
                    models.DecimalField(
                        decimal_places=7, max_digits=12, verbose_name="Latitude NE (norte)"
                    ),
                ),
                (
                    "lng_ne",
                    models.DecimalField(
                        decimal_places=7, max_digits=12, verbose_name="Longitude NE (leste)"
                    ),
                ),
                (
                    "opacidade",
                    models.FloatField(
                        default=0.7,
                        help_text="Entre 0.0 (transparente) e 1.0 (opaco).",
                        verbose_name="Opacidade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "imobiliaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantas_baixas",
                        to="core.imobiliaria",
                        verbose_name="Imobiliária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planta Baixa de Loteamento",
                "verbose_name_plural": "Plantas Baixas de Loteamentos",
                "ordering": ["imobiliaria", "loteamento"],
                "unique_together": {("imobiliaria", "loteamento")},
            },
        ),
    ]
