# Generated by Django 4.2.7 on 2026-04-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_data_parametro_sistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrosistema",
            name="modificado_manualmente",
            field=models.BooleanField(
                default=False,
                help_text="Marcado automaticamente ao salvar pelo admin. Protege o valor de ser sobrescrito pelo sync do .env.",
                verbose_name="Alterado manualmente",
            ),
        ),
    ]
