# Generated by Django 4.2.7 on 2026-05-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_loteamento_overlay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loteamentooverlay",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="loteamentooverlay",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.CreateModel(
            name="AcessoNegado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("url", models.CharField(max_length=500, verbose_name="URL")),
                ("status_code", models.PositiveSmallIntegerField(verbose_name="Status HTTP")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acesso Negado",
                "verbose_name_plural": "Acessos Negados",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["ip", "timestamp"], name="core_acesso_ip_30c586_idx"),
                    models.Index(fields=["timestamp"], name="core_acesso_timesta_091a16_idx"),
                ],
            },
        ),
    ]
