# Generated by Django 4.2.7 on 2026-05-25 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_acesso_negado_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprador",
            name="celular",
            field=models.CharField(blank=True, max_length=20, verbose_name="Celular"),
        ),
        migrations.AlterField(
            model_name="comprador",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail para envio de notificações",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="comprador",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
    ]
