# Generated by Django 4.2.7 on 2026-05-26 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0014_contratoimportacao_store_in_db"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_comprador_contato_opcional"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroUsoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("ANTHROPIC", "Anthropic Claude"), ("GOOGLE", "Google Gemini")],
                        max_length=20,
                        verbose_name="Provedor",
                    ),
                ),
                ("modelo", models.CharField(max_length=60, verbose_name="Modelo")),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("IMPORTACAO_PDF", "Importação de Contrato PDF"),
                            ("CHATBOT_INTENT", "Chatbot — Classificação de Intent"),
                            ("CHATBOT_HUMANIZE", "Chatbot — Humanização de Resposta"),
                        ],
                        max_length=30,
                        verbose_name="Operação",
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(default=0, verbose_name="Tokens entrada"),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(default=0, verbose_name="Tokens saída"),
                ),
                (
                    "custo_usd",
                    models.DecimalField(
                        decimal_places=6, default=0, max_digits=10, verbose_name="Custo (USD)"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora")),
                (
                    "contrato_importacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_uso_ia",
                        to="contratos.contratoimportacao",
                        verbose_name="Importação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_uso_ia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Uso de IA",
                "verbose_name_plural": "Registros de Uso de IA",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["criado_em"], name="core_regist_criado__b8b823_idx"),
                    models.Index(
                        fields=["operacao", "criado_em"], name="core_regist_operaca_85cc40_idx"
                    ),
                    models.Index(
                        fields=["usuario", "criado_em"], name="core_regist_usuario_cdaecc_idx"
                    ),
                ],
            },
        ),
    ]
