# Generated by Django 4.2.7 on 2026-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_registro_uso_ia"),
    ]

    operations = [
        migrations.CreateModel(
            name="LimiteUsoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_escopo",
                    models.CharField(
                        choices=[("MODELO", "Modelo de IA"), ("OPERACAO", "Operação")],
                        max_length=10,
                        verbose_name="Escopo",
                    ),
                ),
                ("escopo_valor", models.CharField(max_length=60, verbose_name="Modelo / Operação")),
                (
                    "tipo_limite",
                    models.CharField(
                        choices=[("TOKENS", "Tokens"), ("REAIS", "R$ (Reais)")],
                        max_length=10,
                        verbose_name="Tipo de limite",
                    ),
                ),
                (
                    "valor_limite",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Limite"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Limite de Uso de IA",
                "verbose_name_plural": "Limites de Uso de IA",
                "ordering": ["tipo_escopo", "escopo_valor"],
                "unique_together": {("tipo_escopo", "escopo_valor", "tipo_limite")},
            },
        ),
    ]
