# Generated by Django 4.2.7 on 2026-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_limite_uso_ia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="limiteusoia",
            options={
                "ordering": ["tipo_escopo", "escopo_valor", "periodo"],
                "verbose_name": "Limite de Uso de IA",
                "verbose_name_plural": "Limites de Uso de IA",
            },
        ),
        migrations.AlterUniqueTogether(
            name="limiteusoia",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="limiteusoia",
            name="periodo",
            field=models.CharField(
                choices=[
                    ("DIARIO", "Diário"),
                    ("SEMANAL", "Semanal"),
                    ("QUINZENAL", "Quinzenal (15 dias)"),
                    ("MENSAL", "Mensal"),
                    ("BIMESTRAL", "Bimestral (2 meses)"),
                    ("SEMESTRAL", "Semestral (6 meses)"),
                    ("ANUAL", "Anual"),
                ],
                default="MENSAL",
                max_length=12,
                verbose_name="Período de reset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="limiteusoia",
            unique_together={("tipo_escopo", "escopo_valor", "tipo_limite", "periodo")},
        ),
    ]
