# Generated by Django 4.2.7 on 2026-05-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_limite_uso_ia_periodo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("PAGAMENTO", "Pagamento registrado"),
                            ("BOLETO_GERADO", "Boleto gerado"),
                            ("REAJUSTE_APLICADO", "Reajuste aplicado"),
                            ("REAJUSTE_DESFEITO", "Reajuste desfeito"),
                            ("CNAB_RETORNO", "CNAB retorno processado"),
                            ("IMPORTACAO_IA", "Importação via IA"),
                            ("EXPORTACAO", "Exportação de relatório"),
                            ("BLOQUEIO_CREDITO", "Bloqueio de crédito ativado"),
                            ("DESBLOQUEIO_CREDITO", "Bloqueio de crédito removido"),
                        ],
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                ("entidade", models.CharField(blank=True, max_length=50, verbose_name="Entidade")),
                (
                    "entidade_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="PK da Entidade"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora")),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="comprador",
            name="bloqueio_credito",
            field=models.BooleanField(
                default=False,
                help_text="Comprador está bloqueado por inadimplência",
                verbose_name="Bloqueio de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="comprador",
            name="bloqueio_credito_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bloqueado em"),
        ),
        migrations.AddField(
            model_name="comprador",
            name="bloqueio_credito_motivo",
            field=models.TextField(blank=True, verbose_name="Motivo do Bloqueio"),
        ),
        migrations.AddIndex(
            model_name="comprador",
            index=models.Index(fields=["bloqueio_credito"], name="core_compra_bloquei_ea87c1_idx"),
        ),
        migrations.AddField(
            model_name="logauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["usuario", "timestamp"], name="core_logaud_usuario_0123c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["entidade", "entidade_pk"], name="core_logaud_entidad_5ff0a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(fields=["acao", "timestamp"], name="core_logaud_acao_ce6ad0_idx"),
        ),
    ]
