# Generated by Django 4.2.7 on 2026-05-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_workflow_ia"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowia",
            name="core_workfl_ativo_idx",
        ),
        migrations.AlterField(
            model_name="workflowia",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="workflowia",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
    ]
