# Generated by Django 4.2.7 on 2026-06-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_fix_workflowia_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="imobiliaria",
            name="cor_marca",
            field=models.CharField(
                blank=True,
                help_text="Hex RRGGBB sem # (ex: 1A4E8C). Cor de destaque nos boletos Prawn.",
                max_length=6,
                verbose_name="Cor de Marca",
            ),
        ),
        migrations.AddField(
            model_name="imobiliaria",
            name="marca_dagua",
            field=models.CharField(
                blank=True,
                help_text="Texto antifraude diagonal no boleto (opcional, máx. 60 chars).",
                max_length=60,
                verbose_name="Marca d'Água",
            ),
        ),
        migrations.AddField(
            model_name="imobiliaria",
            name="rodape_contato",
            field=models.CharField(
                blank=True,
                help_text="Linha de contato no rodapé do boleto. Ex: Tel: (31) 3773-1234 | contato@empresa.com.br",
                max_length=120,
                verbose_name="Rodapé de Contato",
            ),
        ),
    ]
