# Generated by Django 4.2.7 on 2026-06-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_imobiliaria_visual_boleto"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="account_config",
            field=models.JSONField(
                blank=True,
                help_text='Parâmetros bancários sem segredos para o Boleto-API. C6: {"agencia","conta","convenio"}. Sicoob: {"cooperativa","conta","numeroCliente","codigoModalidade"}. Credenciais (client_id/secret/.pfx) ficam no cofre do Boleto-API.',
                null=True,
                verbose_name="Config. da Conta (Boleto-API)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="provider",
            field=models.CharField(
                choices=[
                    ("brcobranca", "BRCobrança (CNAB local/Docker)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="brcobranca",
                help_text="BRCobrança = fluxo CNAB atual; C6/Sicoob = cobrança registrada via Boleto-API.",
                max_length=20,
                verbose_name="Provedor de Cobrança",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                help_text="Identificador do tenant no Boleto-API. Obrigatório para provedores registrados.",
                max_length=100,
                verbose_name="Tenant ID (Boleto-API)",
            ),
        ),
    ]
