# Generated by Django 6.0.6 on 2026-07-15 23:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_boleto_api_provider_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="bapi_token_cifrado",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Token bapi_ devolvido pelo gateway. Use a property `bapi_token`.",
                verbose_name="Token Boleto-API (cifrado)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="bapi_token_criado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Token Boleto-API criado em"
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="credenciais_cifradas",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON cifrado das credenciais de API do banco. Use a property `credenciais`.",
                verbose_name="Credenciais do Banco (cifradas)",
            ),
        ),
        migrations.AddField(
            model_name="imobiliaria",
            name="metodos_cobranca",
            field=models.JSONField(
                blank=True,
                default=core.models.default_metodos_cobranca,
                help_text="Métodos habilitados: boleto, carne, bolepix, pix_automatico.",
                verbose_name="Métodos de Cobrança Disponíveis",
            ),
        ),
        migrations.AlterField(
            model_name="contabancaria",
            name="account_config",
            field=models.JSONField(
                blank=True,
                help_text='Parâmetros bancários SEM segredos para o Boleto-API. C6: {"billing_scheme","chave_pix"}. Sicoob: {"numeroCliente","codigoModalidade","numeroContaCorrente","chave_pix"}. As credenciais (client_id/secret/.pfx/token) ficam cifradas em `credenciais_cifradas` (ver property `credenciais`).',
                null=True,
                verbose_name="Config. da Conta (Boleto-API)",
            ),
        ),
    ]
