# Generated by Django 6.0.6 on 2026-07-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_workflowiatier_modelo_sonnet5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="logauditoria",
            name="acao",
            field=models.CharField(
                choices=[
                    ("PAGAMENTO", "Pagamento registrado"),
                    ("BOLETO_GERADO", "Boleto gerado"),
                    ("REAJUSTE_APLICADO", "Reajuste aplicado"),
                    ("REAJUSTE_DESFEITO", "Reajuste desfeito"),
                    ("CNAB_RETORNO", "CNAB retorno processado"),
                    ("IMPORTACAO_IA", "Importação via IA"),
                    ("EXPORTACAO", "Exportação de relatório"),
                    ("BLOQUEIO_CREDITO", "Bloqueio de crédito ativado"),
                    ("DESBLOQUEIO_CREDITO", "Bloqueio de crédito removido"),
                    ("USUARIO_CRIADO", "Usuário criado"),
                    ("USUARIO_DESATIVADO", "Usuário desativado"),
                    ("ACESSO_CONCEDIDO", "Acesso concedido"),
                    ("ACESSO_NEGADO_ESCOPO", "Acesso negado (fora do escopo)"),
                ],
                max_length=50,
                verbose_name="Ação",
            ),
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("COMUM", "Usuário comum")],
                        default="COMUM",
                        max_length=6,
                        verbose_name="Perfil de acesso",
                    ),
                ),
                (
                    "deve_trocar_senha",
                    models.BooleanField(
                        default=False, verbose_name="Deve trocar senha no próximo acesso"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
    ]
