# Generated by Django 6.0.6 on 2026-07-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_backfill_perfis_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contabancaria",
            name="provider",
            field=models.CharField(
                choices=[
                    ("brcobranca", "pyCobrança (motor offline — boleto/CNAB)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="brcobranca",
                help_text="BRCobrança = fluxo CNAB atual; C6/Sicoob = cobrança registrada via Boleto-API.",
                max_length=20,
                verbose_name="Provedor de Cobrança",
            ),
        ),
    ]
