# Generated by Django 6.0.6 on 2026-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_contabancaria_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contabancaria",
            name="provider",
            field=models.CharField(
                choices=[
                    ("pycobranca", "pyCobrança (motor offline — boleto/CNAB)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="pycobranca",
                help_text="BRCobrança = fluxo CNAB atual; C6/Sicoob = cobrança registrada via Boleto-API.",
                max_length=20,
                verbose_name="Provedor de Cobrança",
            ),
        ),
        migrations.AlterField(
            model_name="parametrosistema",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("email", "E-mail SMTP"),
                    ("twilio", "Twilio (SMS / WhatsApp)"),
                    ("imap", "Bounce / IMAP"),
                    ("teste", "Modo de Teste"),
                    ("notificacao", "Notificações"),
                    ("tarefa", "Tarefas Agendadas"),
                    ("pycobranca", "BRCobrança"),
                    ("portal", "Portal do Comprador"),
                    ("aplicacao", "Aplicação"),
                    ("bcb", "APIs BCB"),
                ],
                default="aplicacao",
                max_length=20,
                verbose_name="Grupo",
            ),
        ),
    ]
