# Generated by Django 6.0.6 on 2026-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_provider_brcobranca_para_pycobranca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrosistema",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("email", "E-mail SMTP"),
                    ("twilio", "Twilio (SMS / WhatsApp)"),
                    ("imap", "Bounce / IMAP"),
                    ("teste", "Modo de Teste"),
                    ("notificacao", "Notificações"),
                    ("tarefa", "Tarefas Agendadas"),
                    ("pycobranca", "pyCobrança (motor offline)"),
                    ("portal", "Portal do Comprador"),
                    ("aplicacao", "Aplicação"),
                    ("bcb", "APIs BCB"),
                ],
                default="aplicacao",
                max_length=20,
                verbose_name="Grupo",
            ),
        ),
    ]
