# Generated by Django 6.0.6 on 2026-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_parametrosistema_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="imobiliaria",
            name="checkout_juros_por",
            field=models.CharField(
                choices=[
                    ("emissor", "Pagador paga o juro (imobiliária recebe o valor cheio)"),
                    ("loja", 'Imobiliária absorve (pagador vê "sem juros")'),
                ],
                default="emissor",
                help_text="No link de pagamento (checkout): quem paga o juro do parcelamento no cartão de crédito.",
                max_length=10,
                verbose_name="Juros do parcelamento no cartão",
            ),
        ),
    ]
