# Generated by Django 6.0.6 on 2026-08-05 18:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_imobiliaria_checkout_juros_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="imobiliaria",
            name="checkout_max_parcelas",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Limite de parcelas oferecido no link de pagamento (1 a 24).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Máximo de parcelas no cartão",
            ),
        ),
        migrations.AddField(
            model_name="imobiliaria",
            name="checkout_valor_minimo_parcela",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor mínimo de cada parcela no link. O nº de parcelas é reduzido para respeitar este piso. 0 = sem piso.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor mínimo por parcela (cartão)",
            ),
        ),
    ]
