# Generated by Django 6.0.6 on 2026-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_imobiliaria_checkout_max_parcelas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="metodos_habilitados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Métodos que esta conta oferece (limitados ao provider): offline → Boleto/Carnê; online → BoletoPix, Pix Automático, Link de pagamento.",
                verbose_name="Métodos de cobrança habilitados",
            ),
        ),
        migrations.AlterField(
            model_name="contabancaria",
            name="provider",
            field=models.CharField(
                choices=[
                    ("pycobranca", "pyCobrança (motor offline — boleto/CNAB)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                    ("inter", "Banco Inter (cobrança registrada)"),
                ],
                default="pycobranca",
                help_text="BRCobrança = fluxo CNAB atual; C6/Sicoob/Inter = cobrança registrada via Boleto-API.",
                max_length=20,
                verbose_name="Provedor de Cobrança",
            ),
        ),
    ]
