# Generated by Django 6.0.6 on 2026-08-07 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_contabancaria_metodos_habilitados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="card_juros_por",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emissor", "Pagador paga o juro (imobiliária recebe o valor cheio)"),
                    ("loja", 'Imobiliária absorve (pagador vê "sem juros")'),
                ],
                default="",
                help_text="Vazio = herda o padrão da imobiliária.",
                max_length=10,
                verbose_name="Juros do parcelamento (cartão)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="card_max_parcelas",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = herda o padrão da imobiliária.",
                validators=[django.core.validators.MaxValueValidator(24)],
                verbose_name="Máximo de parcelas (cartão)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="card_valor_minimo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="0 = herda o padrão da imobiliária.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor mínimo por parcela (cartão)",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="modelo_boleto",
            field=models.CharField(
                choices=[("simples", "Simples"), ("moderno", "Moderno")],
                default="simples",
                help_text="Layout do PDF do boleto emitido por esta conta.",
                max_length=10,
                verbose_name="Modelo do boleto",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="pix_na_tela",
            field=models.BooleanField(
                default=False,
                help_text="Exibe QR/copia-e-cola do Pix direto na tela / 2ª via.",
                verbose_name="Pix na tela",
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="pix_no_link",
            field=models.BooleanField(
                default=False,
                help_text="Inclui o Pix junto no link de pagamento (checkout).",
                verbose_name="Oferecer Pix no link de pagamento",
            ),
        ),
    ]
