# Generated by Django 4.2.7 on 2026-04-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal_comprador", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="acessocomprador",
            name="portal_c_comprad_idx",
        ),
        migrations.RemoveIndex(
            model_name="acessocomprador",
            name="portal_c_usuario_idx",
        ),
        migrations.RemoveIndex(
            model_name="logacessocomprador",
            name="portal_l_acesso_idx",
        ),
    ]
