# Generated by Django 4.2.7 on 2026-05-23 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0017_add_comprovante_upload"),
        ("portal_comprador", "0002_reajuste_spread"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprovantePagamentoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        upload_to="comprovantes_portal/%Y/%m/",
                        verbose_name="Arquivo do Comprovante",
                    ),
                ),
                (
                    "valor_informado",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Pago Informado"
                    ),
                ),
                ("data_pagamento_informada", models.DateField(verbose_name="Data do Pagamento")),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("TED", "Transferência (TED/DOC)"),
                            ("DINHEIRO", "Dinheiro"),
                            ("BOLETO", "Boleto Bancário"),
                            ("OUTRO", "Outro"),
                        ],
                        default="PIX",
                        max_length=15,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "observacoes_comprador",
                    models.TextField(blank=True, verbose_name="Observações do Comprador"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Aguardando Validação"),
                            ("APROVADO", "Aprovado"),
                            ("REJEITADO", "Rejeitado"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "motivo_rejeicao",
                    models.TextField(blank=True, verbose_name="Motivo da Rejeição"),
                ),
                (
                    "validado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Validado em"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Enviado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "acesso_comprador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal_comprador.acessocomprador",
                        verbose_name="Enviado por (Acesso)",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprovantes_upload",
                        to="financeiro.parcela",
                        verbose_name="Parcela",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprovantes_validados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante de Pagamento (Portal)",
                "verbose_name_plural": "Comprovantes de Pagamento (Portal)",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["status", "-criado_em"], name="portal_comp_status_78ef18_idx"
                    ),
                    models.Index(
                        fields=["parcela", "status"], name="portal_comp_parcela_308ba1_idx"
                    ),
                ],
            },
        ),
    ]
