# Generated by Django 4.2.7 on 2026-05-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal_comprador", "0003_add_comprovante_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscriptionPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.TextField(verbose_name="Endpoint Push")),
                ("p256dh", models.TextField(verbose_name="Chave p256dh")),
                ("auth", models.TextField(verbose_name="Auth secret")),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=200, verbose_name="User-Agent"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "acesso_comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to="portal_comprador.acessocomprador",
                        verbose_name="Acesso do comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura Push",
                "verbose_name_plural": "Assinaturas Push",
                "unique_together": {("acesso_comprador", "endpoint")},
            },
        ),
    ]
