# Generated by Django 4.2.7
# Initial migration for financeiro app including boleto fields

from decimal import Decimal
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_original', models.DecimalField(decimal_places=2, help_text='Valor inicial da parcela sem reajustes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Original')),
                ('valor_atual', models.DecimalField(decimal_places=2, help_text='Valor atual da parcela após reajustes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Atual')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Juros calculados por atraso', max_digits=12, verbose_name='Valor de Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multa calculada por atraso', max_digits=12, verbose_name='Valor de Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desconto concedido na parcela', max_digits=12, verbose_name='Valor de Desconto')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                # Campos de Boleto
                ('nosso_numero', models.CharField(blank=True, help_text='Número de identificação do boleto no banco', max_length=30, verbose_name='Nosso Número')),
                ('numero_documento', models.CharField(blank=True, help_text='Número do documento para o cliente', max_length=25, verbose_name='Número do Documento')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras numérico do boleto', max_length=50, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(blank=True, help_text='Linha digitável para pagamento', max_length=60, verbose_name='Linha Digitável')),
                ('boleto_pdf', models.FileField(blank=True, help_text='Arquivo PDF do boleto gerado', null=True, upload_to='boletos/%Y/%m/', verbose_name='Boleto PDF')),
                ('boleto_url', models.URLField(blank=True, help_text='URL externa do boleto (se houver)', max_length=500, verbose_name='URL do Boleto')),
                ('status_boleto', models.CharField(choices=[('NAO_GERADO', 'Não Gerado'), ('GERADO', 'Gerado'), ('REGISTRADO', 'Registrado no Banco'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('PROTESTADO', 'Protestado'), ('BAIXADO', 'Baixado')], default='NAO_GERADO', max_length=15, verbose_name='Status do Boleto')),
                ('data_geracao_boleto', models.DateTimeField(blank=True, help_text='Data/hora em que o boleto foi gerado', null=True, verbose_name='Data de Geração')),
                ('data_registro_boleto', models.DateTimeField(blank=True, help_text='Data/hora em que o boleto foi registrado no banco', null=True, verbose_name='Data de Registro')),
                ('data_pagamento_boleto', models.DateTimeField(blank=True, help_text='Data/hora do pagamento confirmado pelo banco', null=True, verbose_name='Data Pagamento Boleto')),
                ('valor_boleto', models.DecimalField(blank=True, decimal_places=2, help_text='Valor nominal do boleto gerado', max_digits=12, null=True, verbose_name='Valor do Boleto')),
                ('valor_pago_boleto', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente pago via boleto', max_digits=12, null=True, verbose_name='Valor Pago via Boleto')),
                ('banco_pagador', models.CharField(blank=True, help_text='Código do banco onde foi pago', max_length=10, verbose_name='Banco Pagador')),
                ('agencia_pagadora', models.CharField(blank=True, max_length=10, verbose_name='Agência Pagadora')),
                ('motivo_rejeicao', models.CharField(blank=True, help_text='Motivo de rejeição ou baixa do boleto', max_length=255, verbose_name='Motivo Rejeição/Baixa')),
                ('pix_copia_cola', models.TextField(blank=True, help_text='Código PIX para pagamento alternativo', verbose_name='PIX Copia e Cola')),
                ('pix_qrcode', models.TextField(blank=True, help_text='Dados do QR Code PIX em base64', verbose_name='PIX QR Code')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contratos.contrato', verbose_name='Contrato')),
                ('conta_bancaria', models.ForeignKey(blank=True, help_text='Conta bancária usada para gerar o boleto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas', to='core.contabancaria', verbose_name='Conta Bancária')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['contrato', 'numero_parcela'],
            },
        ),
        migrations.CreateModel(
            name='Reajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_reajuste', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Reajuste')),
                ('indice_tipo', models.CharField(help_text='IPCA, IGPM, SELIC, etc.', max_length=10, verbose_name='Tipo de Índice')),
                ('percentual', models.DecimalField(decimal_places=4, help_text='Percentual do índice aplicado', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-100.0000'))], verbose_name='Percentual (%)')),
                ('parcela_inicial', models.PositiveIntegerField(help_text='Primeira parcela afetada pelo reajuste', verbose_name='Parcela Inicial')),
                ('parcela_final', models.PositiveIntegerField(help_text='Última parcela afetada pelo reajuste', verbose_name='Parcela Final')),
                ('aplicado_manual', models.BooleanField(default=False, help_text='Indica se o reajuste foi aplicado manualmente pelo usuário', verbose_name='Aplicado Manualmente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reajustes', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Reajuste',
                'verbose_name_plural': 'Reajustes',
                'ordering': ['-data_reajuste'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Pago')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Juros')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Multa')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Desconto')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CHEQUE', 'Cheque')], default='DINHEIRO', max_length=50, verbose_name='Forma de Pagamento')),
                ('comprovante', models.FileField(blank=True, help_text='Upload do comprovante de pagamento', null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='financeiro.parcela', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['contrato', 'numero_parcela'], name='financeiro__contrat_e7c3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_3df1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['pago'], name='financeiro__pago_50ccf1_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['status_boleto'], name='financeiro__status__7a3b12_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['nosso_numero'], name='financeiro__nosso_n_8d4c21_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcela',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero_parcela'), name='unique_parcela_contrato'),
        ),
        migrations.AddIndex(
            model_name='reajuste',
            index=models.Index(fields=['contrato', 'data_reajuste'], name='financeiro__contrat_2c7e94_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopagamento',
            index=models.Index(fields=['parcela', 'data_pagamento'], name='financeiro__parcela_f1d2c3_idx'),
        ),
    ]
