# Generated by Django 4.2.7 on 2026-03-31 23:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reajuste_desconto_periodo_referencia"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="historicopagamento",
            new_name="financeiro__parcela_804abf_idx",
            old_name="financeiro_h_parc_data_idx",
        ),
        migrations.RenameIndex(
            model_name="itemretorno",
            new_name="financeiro__nosso_n_07db28_idx",
            old_name="financeiro_ir_nosso_idx",
        ),
        migrations.RenameIndex(
            model_name="itemretorno",
            new_name="financeiro__tipo_oc_87e8c8_idx",
            old_name="financeiro_ir_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="parcela",
            new_name="financeiro__contrat_f6af63_idx",
            old_name="financeiro_p_cont_num_idx",
        ),
        migrations.RenameIndex(
            model_name="parcela",
            new_name="financeiro__data_ve_bd885f_idx",
            old_name="financeiro_p_venc_idx",
        ),
        migrations.RenameIndex(
            model_name="parcela",
            new_name="financeiro__pago_451732_idx",
            old_name="financeiro_p_pago_idx",
        ),
        migrations.RenameIndex(
            model_name="parcela",
            new_name="financeiro__status__df4de4_idx",
            old_name="financeiro_p_status_idx",
        ),
        migrations.RenameIndex(
            model_name="parcela",
            new_name="financeiro__nosso_n_33ba47_idx",
            old_name="financeiro_p_nosso_idx",
        ),
        migrations.RenameIndex(
            model_name="reajuste",
            new_name="financeiro__contrat_edba82_idx",
            old_name="financeiro_r_cont_data_idx",
        ),
        migrations.AddField(
            model_name="reajuste",
            name="desconto_percentual",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Redução em p.p. sobre o índice (ex: IPCA 5,4% - 1 p.p. = 4,4%)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Desconto em Pontos Percentuais",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="desconto_valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Desconto fixo em reais subtraído de cada parcela após o percentual",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Desconto em R$ por Parcela",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="percentual_bruto",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percentual calculado do índice antes do desconto",
                max_digits=8,
                null=True,
                verbose_name="Percentual Bruto (%)",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="periodo_referencia_fim",
            field=models.DateField(
                blank=True,
                help_text="Último mês do período cujo acumulado foi utilizado",
                null=True,
                verbose_name="Fim do Período de Referência",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="periodo_referencia_inicio",
            field=models.DateField(
                blank=True,
                help_text="Primeiro mês do período cujo acumulado foi utilizado",
                null=True,
                verbose_name="Início do Período de Referência",
            ),
        ),
        migrations.AlterField(
            model_name="arquivoremessa",
            name="arquivo",
            field=models.FileField(
                help_text="Arquivo CNAB gerado",
                upload_to="cnab/remessa/%Y/%m/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="arquivoremessa",
            name="numero_remessa",
            field=models.PositiveIntegerField(
                help_text="Número sequencial da remessa para esta conta",
                verbose_name="Número da Remessa",
            ),
        ),
        migrations.AlterField(
            model_name="arquivoretorno",
            name="arquivo",
            field=models.FileField(
                help_text="Arquivo CNAB de retorno",
                upload_to="cnab/retorno/%Y/%m/",
                verbose_name="Arquivo",
            ),
        ),
        migrations.AlterField(
            model_name="historicopagamento",
            name="comprovante",
            field=models.FileField(
                blank=True,
                help_text="Upload do comprovante de pagamento",
                null=True,
                upload_to="comprovantes/%Y/%m/",
                verbose_name="Comprovante",
            ),
        ),
        migrations.AlterField(
            model_name="itemremessa",
            name="codigo_ocorrencia",
            field=models.CharField(
                blank=True,
                help_text="Código retornado pelo banco",
                max_length=10,
                verbose_name="Código de Ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="itemremessa",
            name="processado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o retorno já foi processado",
                verbose_name="Processado",
            ),
        ),
        migrations.AlterField(
            model_name="itemretorno",
            name="parcela",
            field=models.ForeignKey(
                blank=True,
                help_text="Parcela identificada (pode ser nulo se não encontrada)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_retorno",
                to="financeiro.parcela",
                verbose_name="Parcela",
            ),
        ),
        migrations.AlterField(
            model_name="itemretorno",
            name="processado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a baixa foi realizada no sistema",
                verbose_name="Processado",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="banco_pagador",
            field=models.CharField(
                blank=True,
                help_text="Código do banco onde foi pago",
                max_length=10,
                verbose_name="Banco Pagador",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="boleto_pdf",
            field=models.FileField(
                blank=True,
                help_text="Arquivo PDF do boleto gerado",
                null=True,
                upload_to="boletos/%Y/%m/",
                verbose_name="Boleto PDF",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="boleto_url",
            field=models.URLField(
                blank=True,
                help_text="URL externa do boleto (se houver)",
                max_length=500,
                verbose_name="URL do Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                help_text="Código de barras numérico do boleto",
                max_length=50,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="conta_bancaria",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta bancária usada para gerar o boleto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcelas",
                to="core.contabancaria",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="data_geracao_boleto",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora em que o boleto foi gerado",
                null=True,
                verbose_name="Data de Geração",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="data_pagamento_boleto",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora do pagamento confirmado pelo banco",
                null=True,
                verbose_name="Data Pagamento Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="data_registro_boleto",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora em que o boleto foi registrado no banco",
                null=True,
                verbose_name="Data de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="linha_digitavel",
            field=models.CharField(
                blank=True,
                help_text="Linha digitável para pagamento",
                max_length=60,
                verbose_name="Linha Digitável",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="motivo_rejeicao",
            field=models.CharField(
                blank=True,
                help_text="Motivo de rejeição ou baixa do boleto",
                max_length=255,
                verbose_name="Motivo Rejeição/Baixa",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="nosso_numero",
            field=models.CharField(
                blank=True,
                help_text="Número de identificação do boleto no banco",
                max_length=30,
                verbose_name="Nosso Número",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="numero_documento",
            field=models.CharField(
                blank=True,
                help_text="Número do documento para o cliente",
                max_length=25,
                verbose_name="Número do Documento",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="pix_copia_cola",
            field=models.TextField(
                blank=True,
                help_text="Código PIX para pagamento alternativo",
                verbose_name="PIX Copia e Cola",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="pix_qrcode",
            field=models.TextField(
                blank=True, help_text="Dados do QR Code PIX em base64", verbose_name="PIX QR Code"
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_atual",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor atual da parcela após reajustes",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor Atual",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_boleto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor nominal do boleto gerado",
                max_digits=12,
                null=True,
                verbose_name="Valor do Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Desconto concedido na parcela",
                max_digits=12,
                verbose_name="Valor de Desconto",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_juros",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Juros calculados por atraso",
                max_digits=12,
                verbose_name="Valor de Juros",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_multa",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Multa calculada por atraso",
                max_digits=12,
                verbose_name="Valor de Multa",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_original",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor inicial da parcela sem reajustes",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor Original",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="valor_pago_boleto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor efetivamente pago via boleto",
                max_digits=12,
                null=True,
                verbose_name="Valor Pago via Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="aplicado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o reajuste já foi efetivamente aplicado nas parcelas",
                verbose_name="Aplicado",
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="aplicado_manual",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o reajuste foi aplicado manualmente pelo usuário",
                verbose_name="Aplicado Manualmente",
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="data_aplicacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora em que o reajuste foi aplicado",
                null=True,
                verbose_name="Data da Aplicação",
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="data_limite_boleto",
            field=models.DateField(
                blank=True,
                help_text="Data até quando boletos podem ser gerados após este reajuste",
                null=True,
                verbose_name="Data Limite para Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="indice_tipo",
            field=models.CharField(
                help_text="IPCA, IGPM, SELIC, etc.", max_length=10, verbose_name="Tipo de Índice"
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="parcela_final",
            field=models.PositiveIntegerField(
                help_text="Última parcela afetada pelo reajuste", verbose_name="Parcela Final"
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="parcela_inicial",
            field=models.PositiveIntegerField(
                help_text="Primeira parcela afetada pelo reajuste", verbose_name="Parcela Inicial"
            ),
        ),
        migrations.AlterField(
            model_name="reajuste",
            name="percentual",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Percentual do índice aplicado",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("-100.0000"))],
                verbose_name="Percentual (%)",
            ),
        ),
        migrations.AddIndex(
            model_name="arquivoremessa",
            index=models.Index(
                fields=["conta_bancaria", "numero_remessa"], name="financeiro__conta_b_2f8fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arquivoremessa",
            index=models.Index(fields=["status"], name="financeiro__status_38bb96_idx"),
        ),
        migrations.AddIndex(
            model_name="arquivoremessa",
            index=models.Index(fields=["data_geracao"], name="financeiro__data_ge_22607e_idx"),
        ),
        migrations.AddIndex(
            model_name="arquivoretorno",
            index=models.Index(fields=["conta_bancaria"], name="financeiro__conta_b_c24842_idx"),
        ),
        migrations.AddIndex(
            model_name="arquivoretorno",
            index=models.Index(fields=["status"], name="financeiro__status_b08bda_idx"),
        ),
        migrations.AddIndex(
            model_name="arquivoretorno",
            index=models.Index(fields=["data_upload"], name="financeiro__data_up_1f8a1a_idx"),
        ),
        migrations.AddIndex(
            model_name="itemretorno",
            index=models.Index(fields=["codigo_ocorrencia"], name="financeiro__codigo__30ca13_idx"),
        ),
    ]
