# Generated by Django 4.2.7 on 2026-04-01 00:00
# Reescrito com SeparateDatabaseAndState + ADD COLUMN IF NOT EXISTS para ser idempotente.
# Contexto: em produção a coluna pode já existir (adicionada manualmente ou por build.sh).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0002_reajuste_desconto_periodo_referencia"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS ip_address inet NULL;",
                    reverse_sql="ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS ip_address;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reajuste",
                    name="ip_address",
                    field=models.GenericIPAddressField(
                        blank=True,
                        help_text="IP do usuário que aplicou o reajuste",
                        null=True,
                        verbose_name="Endereço IP",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS piso_aplicado numeric(8,4) NULL;",
                    reverse_sql="ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS piso_aplicado;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reajuste",
                    name="piso_aplicado",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Piso de reajuste vigente no contrato no momento da aplicação",
                        max_digits=8,
                        null=True,
                        verbose_name="Piso Aplicado (%)",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS teto_aplicado numeric(8,4) NULL;",
                    reverse_sql="ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS teto_aplicado;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reajuste",
                    name="teto_aplicado",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Teto de reajuste vigente no contrato no momento da aplicação",
                        max_digits=8,
                        null=True,
                        verbose_name="Teto Aplicado (%)",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS usuario_id integer NULL;",
                    reverse_sql="ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS usuario_id;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reajuste",
                    name="usuario",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Usuário que aplicou o reajuste",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reajustes_aplicados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
