# Generated by Django 4.2.7 on 2026-04-01 00:00
# Reescrito com SeparateDatabaseAndState + RunPython para ser idempotente em PostgreSQL
# e compatível com SQLite (testes).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_reajuste_columns(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS ip_address inet NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS piso_aplicado numeric(8,4) NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS teto_aplicado numeric(8,4) NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN IF NOT EXISTS usuario_id integer NULL;"
        )
    else:
        # SQLite (test environment): test DB is always fresh, no IF NOT EXISTS needed
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN ip_address TEXT NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN piso_aplicado NUMERIC(8,4) NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN teto_aplicado NUMERIC(8,4) NULL;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste ADD COLUMN usuario_id INTEGER NULL;"
        )


def remove_reajuste_columns(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS ip_address;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS piso_aplicado;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS teto_aplicado;"
        )
        schema_editor.execute(
            "ALTER TABLE financeiro_reajuste DROP COLUMN IF EXISTS usuario_id;"
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0002_reajuste_desconto_periodo_referencia"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_reajuste_columns, remove_reajuste_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="reajuste",
                    name="ip_address",
                    field=models.GenericIPAddressField(
                        blank=True,
                        help_text="IP do usuário que aplicou o reajuste",
                        null=True,
                        verbose_name="Endereço IP",
                    ),
                ),
                migrations.AddField(
                    model_name="reajuste",
                    name="piso_aplicado",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Piso de reajuste vigente no contrato no momento da aplicação",
                        max_digits=8,
                        null=True,
                        verbose_name="Piso Aplicado (%)",
                    ),
                ),
                migrations.AddField(
                    model_name="reajuste",
                    name="teto_aplicado",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Teto de reajuste vigente no contrato no momento da aplicação",
                        max_digits=8,
                        null=True,
                        verbose_name="Teto Aplicado (%)",
                    ),
                ),
                migrations.AddField(
                    model_name="reajuste",
                    name="usuario",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Usuário que aplicou o reajuste",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reajustes_aplicados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
