# Generated by Django 4.2.7 on 2026-04-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0002_reajuste_desconto_periodo_referencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="reajuste",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP do usuário que aplicou o reajuste",
                null=True,
                verbose_name="Endereço IP",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="piso_aplicado",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Piso de reajuste vigente no contrato no momento da aplicação",
                max_digits=8,
                null=True,
                verbose_name="Piso Aplicado (%)",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="teto_aplicado",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Teto de reajuste vigente no contrato no momento da aplicação",
                max_digits=8,
                null=True,
                verbose_name="Teto Aplicado (%)",
            ),
        ),
        migrations.AddField(
            model_name="reajuste",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário que aplicou o reajuste",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reajustes_aplicados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
