# Generated by Django 4.2.7 on 2026-04-01 01:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_contrato_reajuste_piso_teto"),
    ]

    operations = [
        migrations.AddField(
            model_name="reajuste",
            name="spread_aplicado",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=Decimal("0"),
                help_text="Pontos percentuais de spread adicionados ao índice bruto",
                max_digits=8,
                null=True,
                verbose_name="Spread Aplicado (p.p.)",
            ),
        ),
    ]
