# Generated by Django 4.2.7 on 2026-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_reajuste_spread"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="amortizacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Parcela de amortização do principal embutida nesta prestação",
                max_digits=12,
                null=True,
                verbose_name="Amortização",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="juros_embutido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Parcela de juros do financiamento embutida nesta prestação",
                max_digits=12,
                null=True,
                verbose_name="Juros Embutidos",
            ),
        ),
    ]
