# Generated by Django 4.2.7 on 2026-04-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_historicopagamento_antecipado"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["pago", "data_vencimento"], name="fin_parcela_pago_venc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["contrato", "pago", "data_vencimento"],
                name="fin_parcela_ctrt_pago_venc_idx",
            ),
        ),
    ]
