# Generated by Django 4.2.7 on 2026-04-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_add_vencimento_compound_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="boleto_pdf_db",
            field=models.BinaryField(
                blank=True,
                help_text="Cópia do PDF em banco de dados — persiste em storage efêmero (Render)",
                null=True,
                verbose_name="PDF do boleto (banco de dados)",
            ),
        ),
    ]
