# Generated by Django 4.2.7 on 2026-04-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_add_boleto_pdf_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicopagamento",
            name="fitid_ofx",
            field=models.CharField(
                blank=True,
                help_text="ID único da transação no arquivo OFX — usado para deduplicação",
                max_length=255,
                verbose_name="FITID OFX",
            ),
        ),
        migrations.AddField(
            model_name="historicopagamento",
            name="item_retorno",
            field=models.ForeignKey(
                blank=True,
                help_text="Vínculo ao registro do arquivo de retorno CNAB que gerou este pagamento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historico_pagamentos",
                to="financeiro.itemretorno",
                verbose_name="Item Retorno CNAB",
            ),
        ),
        migrations.AddField(
            model_name="historicopagamento",
            name="origem_pagamento",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CNAB", "Retorno CNAB"),
                    ("OFX", "Extrato OFX"),
                    ("ANTECIPACAO", "Antecipação"),
                    ("SISTEMA", "Sistema"),
                ],
                default="MANUAL",
                help_text="Como o pagamento foi registrado: manual, retorno CNAB, extrato OFX ou antecipação",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
        migrations.AddIndex(
            model_name="historicopagamento",
            index=models.Index(fields=["origem_pagamento"], name="financeiro__origem__650baf_idx"),
        ),
        migrations.AddIndex(
            model_name="historicopagamento",
            index=models.Index(fields=["fitid_ofx"], name="financeiro__fitid_o_428052_idx"),
        ),
        # NOTA: A constraint unique_nosso_numero_nao_vazio (global) não é criada no DB
        # porque produção já pode ter nosso_numero duplicados entre contas bancárias.
        # O estado Django registra a constraint para consistência; a constraint real
        # (por conta bancária) é criada na migration 0011.
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # não cria no DB — pode falhar com duplicatas
            state_operations=[
                migrations.AddConstraint(
                    model_name="parcela",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("nosso_numero", ""), _negated=True),
                        fields=("nosso_numero",),
                        name="unique_nosso_numero_nao_vazio",
                    ),
                ),
            ],
        ),
    ]
