# Generated by Django 4.2.7 on 2026-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0010_add_conciliacao_nossonumero_unico_historico_origem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="parcela",
            name="unique_nosso_numero_nao_vazio",
        ),
        migrations.AddConstraint(
            model_name="parcela",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nosso_numero", ""), _negated=True),
                fields=("conta_bancaria", "nosso_numero"),
                name="unique_nosso_numero_por_conta",
            ),
        ),
    ]
