# Generated by Django 4.2.7 on 2026-04-10 02:08
# Modified: usar SeparateDatabaseAndState para remover constraint com IF EXISTS,
# garantindo que a migration funcione mesmo quando unique_nosso_numero_nao_vazio
# não foi criada no DB (produção com nosso_numero duplicados entre contas).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0010_add_conciliacao_nossonumero_unico_historico_origem"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # No DB: remove o índice com IF EXISTS (seguro mesmo se não existir)
            # e cria a nova constraint por conta bancária.
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS unique_nosso_numero_nao_vazio;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.AddConstraint(
                    model_name="parcela",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("nosso_numero", ""), _negated=True),
                        fields=("conta_bancaria", "nosso_numero"),
                        name="unique_nosso_numero_por_conta",
                    ),
                ),
            ],
            # No estado Django: remove a constraint global (registrada em 0010)
            # e adiciona a constraint por conta bancária.
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="parcela",
                    name="unique_nosso_numero_nao_vazio",
                ),
                migrations.AddConstraint(
                    model_name="parcela",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("nosso_numero", ""), _negated=True),
                        fields=("conta_bancaria", "nosso_numero"),
                        name="unique_nosso_numero_por_conta",
                    ),
                ),
            ],
        ),
    ]
