# Generated by Django 4.2.7 on 2026-05-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0013_parcela_token_publico"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="token_expira_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Deixe em branco para não expirar. Preenchido automaticamente na geração do boleto.",
                null=True,
                verbose_name="Token expira em",
            ),
        ),
        migrations.CreateModel(
            name="AcessoBoletoPublico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="User-Agent"),
                ),
                (
                    "acessado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Acessado em"),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos_publicos",
                        to="financeiro.parcela",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acesso Boleto Público",
                "verbose_name_plural": "Acessos Boleto Público",
                "ordering": ["-acessado_em"],
                "indexes": [
                    models.Index(
                        fields=["parcela", "acessado_em"], name="financeiro__parcela_8d3dfd_idx"
                    ),
                    models.Index(fields=["ip", "acessado_em"], name="financeiro__ip_c70437_idx"),
                ],
            },
        ),
    ]
