# Generated by Django 4.2.7 on 2026-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0014_parcela_token_expira_e_acesso_publico"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reajuste",
            index=models.Index(
                fields=["contrato", "ciclo", "aplicado"], name="fin_reajuste_ciclo_aplic"
            ),
        ),
    ]
