# Generated by Django 4.2.7 on 2026-05-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0015_add_reajuste_ciclo_aplicado_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="pix_txid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID de transação PIX (até 35 chars — padrão BCB) usado para reconciliação via webhook",
                max_length=35,
                verbose_name="PIX txid",
            ),
        ),
        migrations.CreateModel(
            name="EventoPIX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "end_to_end_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da transação PIX — usado para deduplicação",
                        max_length=35,
                        unique=True,
                        verbose_name="EndToEndId",
                    ),
                ),
                (
                    "txid",
                    models.CharField(blank=True, db_index=True, max_length=35, verbose_name="txid"),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Valor"),
                ),
                ("horario_pix", models.DateTimeField(verbose_name="Horário do PIX")),
                (
                    "pagador_nome",
                    models.CharField(blank=True, max_length=200, verbose_name="Pagador"),
                ),
                (
                    "pagador_documento",
                    models.CharField(blank=True, max_length=20, verbose_name="CPF/CNPJ Pagador"),
                ),
                ("info_pagador", models.TextField(blank=True, verbose_name="Info Pagador")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEBIDO", "Recebido"),
                            ("BAIXADO", "Parcela Baixada"),
                            ("DUPLICADO", "Duplicado (ignorado)"),
                            ("SEM_PARCELA", "Sem Parcela Vinculada"),
                            ("ERRO", "Erro no Processamento"),
                        ],
                        default="RECEBIDO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="Erro")),
                (
                    "payload_raw",
                    models.TextField(
                        help_text="JSON completo enviado pelo PSP para fins de auditoria",
                        verbose_name="Payload Raw",
                    ),
                ),
                (
                    "recebido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_pix",
                        to="financeiro.parcela",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento PIX",
                "verbose_name_plural": "Eventos PIX",
                "ordering": ["-recebido_em"],
                "indexes": [
                    models.Index(fields=["txid"], name="financeiro__txid_c5d527_idx"),
                    models.Index(fields=["status"], name="financeiro__status_856926_idx"),
                    models.Index(fields=["recebido_em"], name="financeiro__recebid_0bc7e2_idx"),
                ],
            },
        ),
    ]
