# Generated by Django 4.2.7 on 2026-05-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0016_add_pix_txid_and_evento_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicopagamento",
            name="origem_pagamento",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CNAB", "Retorno CNAB"),
                    ("OFX", "Extrato OFX"),
                    ("ANTECIPACAO", "Antecipação"),
                    ("PIX_WEBHOOK", "PIX Webhook"),
                    ("PORTAL_UPLOAD", "Upload pelo Portal do Comprador"),
                    ("SISTEMA", "Sistema"),
                ],
                default="MANUAL",
                help_text="Como o pagamento foi registrado: manual, retorno CNAB, extrato OFX ou antecipação",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
    ]
