# Generated by Django 4.2.7 on 2026-06-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0017_add_comprovante_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivoremessa",
            name="data_download",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o arquivo .rem foi baixado pela primeira vez (habilita o estado BAIXADO)",
                null=True,
                verbose_name="Data do 1º Download",
            ),
        ),
        migrations.AddField(
            model_name="arquivoremessa",
            name="enviado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remessas_enviadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enviado por",
            ),
        ),
        migrations.AddField(
            model_name="arquivoremessa",
            name="gerado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remessas_geradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerado por",
            ),
        ),
    ]
