# Generated by Django 4.2.7 on 2026-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0018_arquivoremessa_data_download_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemremessa",
            name="motivo_rejeicao",
            field=models.CharField(blank=True, max_length=255, verbose_name="Motivo da Rejeição"),
        ),
        migrations.AddField(
            model_name="itemremessa",
            name="status",
            field=models.CharField(
                choices=[("ATIVO", "Ativo"), ("REJEITADO", "Rejeitado pelo Banco")],
                default="ATIVO",
                help_text="REJEITADO quando o banco recusou o registro (boleto volta a ser elegível)",
                max_length=10,
                verbose_name="Status do Item",
            ),
        ),
    ]
