# Generated by Django 4.2.7 on 2026-06-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0019_itemremessa_motivo_rejeicao_itemremessa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="cobranca_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID retornado pelo Boleto-API ao registrar a cobrança. Usado para casamento no webhook push.",
                max_length=100,
                verbose_name="ID Cobrança (Boleto-API)",
            ),
        ),
        migrations.CreateModel(
            name="EventoCobrancaApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cobranca_id",
                    models.CharField(db_index=True, max_length=100, verbose_name="ID Cobrança"),
                ),
                (
                    "event",
                    models.CharField(blank=True, max_length=50, verbose_name="Tipo de Evento"),
                ),
                (
                    "status_cobranca",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Status no Boleto-API"
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Pago em")),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("baixado", "Parcela baixada"),
                            ("duplicado", "Duplicado (ignorado)"),
                            ("sem_parcela", "Sem parcela vinculada"),
                            ("erro", "Erro no processamento"),
                        ],
                        default="recebido",
                        max_length=20,
                        verbose_name="Status de Processamento",
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="Erro")),
                (
                    "payload_raw",
                    models.TextField(
                        blank=True,
                        help_text="JSON completo para auditoria",
                        verbose_name="Payload Raw",
                    ),
                ),
                (
                    "recebido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_cobranca_api",
                        to="financeiro.parcela",
                        verbose_name="Parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Cobrança API",
                "verbose_name_plural": "Eventos Cobrança API",
                "ordering": ["-recebido_em"],
                "indexes": [
                    models.Index(fields=["cobranca_id"], name="financeiro__cobranc_3c8469_idx"),
                    models.Index(fields=["status"], name="financeiro__status_60642b_idx"),
                    models.Index(fields=["recebido_em"], name="financeiro__recebid_301e46_idx"),
                ],
            },
        ),
    ]
