# Generated by Django 6.0.6 on 2026-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0020_parcela_cobranca_id_evento_cobranca_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="ext_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="ext_ref devolvido pelo gateway para BoletoPix. Usado no casamento do webhook.",
                max_length=100,
                verbose_name="Referência Externa (bolepix)",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="metodo_cobranca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boleto", "Boleto registrado"),
                    ("carne", "Carnê"),
                    ("bolepix", "Boleto + Pix (BoletoPix)"),
                    ("pix_automatico", "Pix Automático (débito recorrente)"),
                ],
                default="",
                help_text="Método usado nesta cobrança (boleto/carne/bolepix/pix_automatico).",
                max_length=20,
                verbose_name="Método da Cobrança",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brcobranca", "BRCobrança (CNAB local/Docker)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="",
                help_text="Provedor que emitiu esta cobrança (registrado na emissão).",
                max_length=20,
                verbose_name="Provedor da Cobrança",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="status_cobranca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendente", "Pendente"),
                    ("registrada", "Registrada"),
                    ("aguardando_cip", "Aguardando CIP"),
                    ("liquidada", "Liquidada"),
                    ("baixada", "Baixada"),
                    ("expirada", "Expirada"),
                    ("estornada", "Estornada"),
                ],
                db_index=True,
                default="",
                help_text="Status transversal (boleto/pix). Vazio = ainda não emitida via Boleto-API.",
                max_length=20,
                verbose_name="Status Normalizado da Cobrança",
            ),
        ),
    ]
