# Generated by Django 6.0.6 on 2026-07-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0021_parcela_ext_ref_parcela_metodo_cobranca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventocobrancaapi",
            name="event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Identificador único do evento (idempotência).",
                max_length=100,
                verbose_name="ID do Evento",
            ),
        ),
        migrations.AlterField(
            model_name="eventocobrancaapi",
            name="status",
            field=models.CharField(
                choices=[
                    ("recebido", "Recebido"),
                    ("baixado", "Parcela baixada"),
                    ("atualizado", "Status atualizado"),
                    ("duplicado", "Duplicado (ignorado)"),
                    ("ignorado", "Ignorado (não tratado nesta fase)"),
                    ("sem_parcela", "Sem parcela vinculada"),
                    ("erro", "Erro no processamento"),
                ],
                default="recebido",
                max_length=20,
                verbose_name="Status de Processamento",
            ),
        ),
        migrations.AddIndex(
            model_name="eventocobrancaapi",
            index=models.Index(fields=["event_id"], name="financeiro__event_i_7aca0f_idx"),
        ),
    ]
