# Generated by Django 6.0.6 on 2026-07-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0015_contrato_metodo_cobranca"),
        ("financeiro", "0022_eventocobrancaapi_event_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecorrenciaPix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "id_rec",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="idRec (gateway)",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brcobranca", "BRCobrança (CNAB local/Docker)"),
                            ("c6", "C6 Bank (cobrança registrada)"),
                            ("sicoob", "Sicoob (cobrança registrada)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CRIADA", "Criada"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        db_index=True,
                        default="CRIADA",
                        max_length=20,
                    ),
                ),
                ("aprovada_em", models.DateTimeField(blank=True, null=True)),
                ("cancelada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorrencia_pix",
                        to="contratos.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recorrência Pix Automático",
                "verbose_name_plural": "Recorrências Pix Automático",
            },
        ),
    ]
