# Generated by Django 6.0.6 on 2026-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0025_alter_parcela_provider_alter_recorrenciapix_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcela",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pycobranca", "pyCobrança (motor offline — boleto/CNAB)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="",
                help_text="Provedor que emitiu esta cobrança (registrado na emissão).",
                max_length=20,
                verbose_name="Provedor da Cobrança",
            ),
        ),
        migrations.AlterField(
            model_name="recorrenciapix",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pycobranca", "pyCobrança (motor offline — boleto/CNAB)"),
                    ("c6", "C6 Bank (cobrança registrada)"),
                    ("sicoob", "Sicoob (cobrança registrada)"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
