# Generated by Django 6.0.6 on 2026-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0027_rename_provider_brcobranca_para_pycobranca"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="checkout_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL do checkout hospedado (cartão/Pix) devolvida pela cobranca-api V2.2.",
                max_length=500,
                verbose_name="Link de pagamento (checkout)",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="metodo_cobranca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boleto", "Boleto registrado"),
                    ("carne", "Carnê"),
                    ("bolepix", "Boleto + Pix (BoletoPix)"),
                    ("pix_automatico", "Pix Automático (débito recorrente)"),
                    ("checkout", "Link de pagamento (cartão/Pix)"),
                ],
                default="",
                help_text="Método usado nesta cobrança (boleto/carne/bolepix/pix_automatico).",
                max_length=20,
                verbose_name="Método da Cobrança",
            ),
        ),
    ]
