# Generated by Django 4.2.7 on 2026-04-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificacao",
            new_name="notificacoe_status_ab23c5_idx",
            old_name="notificacoe_status_b79a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="notificacao",
            new_name="notificacoe_parcela_e7cca6_idx",
            old_name="notificacoe_parcela_f95d9b_idx",
        ),
    ]
