# Generated by Django 4.2.7 on 2026-04-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0002_reajuste_spread"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraNotificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da Regra")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "tipo_gatilho",
                    models.CharField(
                        choices=[
                            ("ANTES", "Dias antes do vencimento"),
                            ("APOS", "Dias após o vencimento (inadimplência)"),
                        ],
                        help_text="Momento de envio em relação ao vencimento da parcela",
                        max_length=5,
                        verbose_name="Gatilho",
                    ),
                ),
                (
                    "dias_offset",
                    models.PositiveIntegerField(
                        help_text="Número de dias antes/após o vencimento para disparar",
                        verbose_name="Dias",
                    ),
                ),
                (
                    "tipo_notificacao",
                    models.CharField(
                        choices=[("EMAIL", "E-mail"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp")],
                        default="EMAIL",
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deixe vazio para usar a mensagem padrão do sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regras",
                        to="notificacoes.templatenotificacao",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Notificação",
                "verbose_name_plural": "Régua de Notificação",
                "ordering": ["tipo_gatilho", "dias_offset"],
                "unique_together": {("tipo_gatilho", "dias_offset", "tipo_notificacao")},
            },
        ),
    ]
