# Generated by Django 4.2.7 on 2026-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0003_add_regra_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Evolution: apikey do cabeçalho | Z-API: token da instância",
                max_length=255,
                verbose_name="API Key / Token",
            ),
        ),
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="api_url",
            field=models.URLField(
                blank=True,
                help_text="Evolution: http://seu-servidor:8080 | Z-API: https://api.z-api.io",
                verbose_name="URL da API",
            ),
        ),
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="client_token",
            field=models.CharField(
                blank=True,
                help_text="Cabeçalho Client-Token exigido pela Z-API",
                max_length=255,
                verbose_name="Client-Token (Z-API)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="instancia",
            field=models.CharField(
                blank=True,
                help_text="Evolution: nome da instância | Z-API: instance ID",
                max_length=100,
                verbose_name="Instância / Instance",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaowhatsapp",
            name="account_sid",
            field=models.CharField(blank=True, max_length=255, verbose_name="Account SID"),
        ),
        migrations.AlterField(
            model_name="configuracaowhatsapp",
            name="auth_token",
            field=models.CharField(blank=True, max_length=255, verbose_name="Auth Token"),
        ),
        migrations.AlterField(
            model_name="configuracaowhatsapp",
            name="numero_remetente",
            field=models.CharField(
                blank=True,
                help_text="Twilio/Meta: whatsapp:+5511999999999 | Z-API: número sem prefixo",
                max_length=30,
                verbose_name="Número WhatsApp Remetente",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaowhatsapp",
            name="provedor",
            field=models.CharField(
                choices=[
                    ("TWILIO", "Twilio"),
                    ("META", "Meta (WhatsApp Business API)"),
                    ("EVOLUTION", "Evolution API (self-hosted)"),
                    ("ZAPI", "Z-API"),
                ],
                default="TWILIO",
                max_length=50,
                verbose_name="Provedor",
            ),
        ),
    ]
