# Generated by Django 4.2.7 on 2026-04-10
# Adiciona campos de rastreamento de entrega ao modelo Notificacao:
#   - external_id: Twilio MessageSid ou Message-ID do e-mail
#   - status_entrega: status confirmado pelo provedor (queued/sent/delivered/failed/...)
#   - data_confirmacao: timestamp do callback de entrega
# + índice em external_id para lookup eficiente no webhook Twilio

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_template_unificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='external_id',
            field=models.CharField(
                blank=True,
                help_text='Twilio MessageSid ou Message-ID do e-mail para rastreamento',
                max_length=255,
                verbose_name='ID Externo',
            ),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='status_entrega',
            field=models.CharField(
                blank=True,
                choices=[
                    ('accepted', 'Aceito'),
                    ('queued', 'Enfileirado'),
                    ('sending', 'Enviando'),
                    ('sent', 'Enviado'),
                    ('delivered', 'Entregue'),
                    ('undelivered', 'Não entregue'),
                    ('failed', 'Falhou'),
                    ('read', 'Lido'),
                ],
                help_text='Status confirmado pelo provedor: queued, sending, sent, delivered, undelivered, failed, read',
                max_length=20,
                verbose_name='Status de Entrega',
            ),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_confirmacao',
            field=models.DateTimeField(
                blank=True,
                help_text='Quando o provedor confirmou a entrega ou falha via webhook',
                null=True,
                verbose_name='Data de Confirmação',
            ),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['external_id'], name='notif_external_id_idx'),
        ),
    ]
