# Generated by Django 4.2.7 on 2026-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0007_update_templates_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="status_entrega",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Aceito"),
                    ("queued", "Enfileirado"),
                    ("sending", "Enviando"),
                    ("sent", "Enviado"),
                    ("delivered", "Entregue"),
                    ("undelivered", "Não entregue"),
                    ("failed", "Falhou"),
                    ("read", "Lido"),
                    ("clicked", "Clicado (link)"),
                    ("bounced", "Bounce (NDR)"),
                    ("opened", "Aberto (pixel)"),
                ],
                help_text="Status confirmado pelo provedor: queued, sending, sent, delivered, undelivered, failed, read",
                max_length=20,
                verbose_name="Status de Entrega",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="assunto",
            field=models.CharField(
                blank=True,
                help_text="Assunto do e-mail. Suporta TAGs como %%NOMECOMPRADOR%%",
                max_length=255,
                verbose_name="Assunto (E-mail)",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("BOLETO_CRIADO", "Boleto Criado"),
                    ("BOLETO_5_DIAS", "Boleto - 5 dias para vencer"),
                    ("BOLETO_VENCE_AMANHA", "Boleto - Vence amanhã"),
                    ("BOLETO_VENCEU_ONTEM", "Boleto - Venceu ontem"),
                    ("BOLETO_VENCIDO", "Boleto Vencido"),
                    ("PAGAMENTO_CONFIRMADO", "Pagamento Confirmado"),
                    ("CONTRATO_CRIADO", "Contrato Criado"),
                    ("LEMBRETE_PARCELA", "Lembrete de Parcela"),
                    ("RELATORIO_MENSAL", "Relatório Mensal"),
                    ("RELATORIO_SEMANAL", "Relatório Semanal"),
                    ("CUSTOM", "Personalizado"),
                ],
                default="CUSTOM",
                max_length=30,
                verbose_name="Tipo do Template",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="corpo",
            field=models.TextField(
                blank=True,
                help_text="Texto para SMS (máx. 255 caracteres). Use TAGs como %%NOMECOMPRADOR%%.",
                verbose_name="Corpo SMS",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="corpo_html",
            field=models.TextField(
                blank=True,
                help_text="Conteúdo HTML do e-mail. Suporta TAGs %%TAG%%.",
                verbose_name="Corpo E-mail (HTML)",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="corpo_whatsapp",
            field=models.TextField(
                blank=True,
                help_text="Texto para mensagem WhatsApp. Suporta TAGs %%TAG%%.",
                verbose_name="Corpo WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="templatenotificacao",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("EMAIL", "E-mail"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp")],
                help_text="Legado — canal determinado automaticamente pelos campos preenchidos",
                max_length=20,
                null=True,
                verbose_name="Canal de Envio",
            ),
        ),
    ]
