# Generated by Django 4.2.7 on 2026-05-05 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_parametro_modificado_manualmente"),
        ("notificacoes", "0008_alter_notificacao_status_entrega_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoConversaWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "numero_whatsapp",
                    models.CharField(
                        db_index=True,
                        help_text='E.164 sem "+", ex: 5511999999999',
                        max_length=30,
                        verbose_name="Número WhatsApp",
                    ),
                ),
                (
                    "instancia",
                    models.CharField(max_length=100, verbose_name="Instância Evolution API"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INICIO", "Aguardando identificação"),
                            ("AGUARDA_CPF", "Aguardando CPF"),
                            ("MENU", "Menu principal"),
                            ("AGUARDA_SELECAO_BOLETO", "Aguardando seleção de boleto"),
                            ("AGUARDA_COMPROVANTE", "Aguardando comprovante"),
                            ("ENCERRADA", "Encerrada"),
                        ],
                        default="INICIO",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexto temporário: ids de parcelas exibidas, tentativas, etc.",
                        verbose_name="Dados de contexto",
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "comprador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessoes_whatsapp",
                        to="core.comprador",
                        verbose_name="Comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Conversa WhatsApp",
                "verbose_name_plural": "Sessões de Conversa WhatsApp",
                "indexes": [
                    models.Index(
                        fields=["numero_whatsapp", "ativo"], name="notificacoe_numero__d5b376_idx"
                    )
                ],
            },
        ),
    ]
