# Generated by Django 4.2.7 on 2026-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0010_templates_relatorio_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatenotificacao",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("BOLETO_CRIADO", "Boleto Criado"),
                    ("BOLETO_5_DIAS", "Boleto - 5 dias para vencer"),
                    ("BOLETO_VENCE_AMANHA", "Boleto - Vence amanhã"),
                    ("BOLETO_VENCEU_ONTEM", "Boleto - Venceu ontem"),
                    ("BOLETO_VENCIDO", "Boleto Vencido"),
                    ("PAGAMENTO_CONFIRMADO", "Pagamento Confirmado"),
                    ("CONTRATO_CRIADO", "Contrato Criado"),
                    ("LEMBRETE_PARCELA", "Lembrete de Parcela"),
                    ("RELATORIO_MENSAL", "Relatório Mensal"),
                    ("RELATORIO_SEMANAL", "Relatório Semanal"),
                    ("gestao-relatorio-mensal", "Gestão — Relatório Mensal"),
                    ("gestao-relatorio-semanal", "Gestão — Relatório Semanal"),
                    ("CUSTOM", "Personalizado"),
                ],
                default="CUSTOM",
                max_length=30,
                verbose_name="Tipo do Template",
            ),
        ),
    ]
