# Generated by Django 4.2.7 on 2026-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0012_templates_gestao_relatorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="meta_access_token",
            field=models.CharField(
                blank=True,
                help_text="Meta Cloud API: token de acesso permanente do Meta Business.",
                max_length=512,
                verbose_name="Access Token Meta (Cloud API)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="modo_evolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAILEYS", "Baileys (self-hosted padrão)"),
                    ("CLOUD_API", "Cloud API (Meta oficial)"),
                ],
                default="BAILEYS",
                help_text="BAILEYS: instância local via QR Code. CLOUD_API: usa Meta Cloud API oficial.",
                max_length=10,
                verbose_name="Modo Evolution",
            ),
        ),
        migrations.AddField(
            model_name="configuracaowhatsapp",
            name="phone_number_id",
            field=models.CharField(
                blank=True,
                help_text="Meta Cloud API: ID do número de telefone no Meta Business.",
                max_length=50,
                verbose_name="Phone Number ID (Cloud API)",
            ),
        ),
    ]
