# Generated by Django 4.2.7 on 2026-05-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0013_add_evolution_cloud_api_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprovantePendente",
            fields=[],
            options={
                "verbose_name": "Comprovante Pendente",
                "verbose_name_plural": "Comprovantes Pendentes de Revisão",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notificacoes.notificacao",),
        ),
    ]
