# Generated by Django 4.2.7 on 2026-05-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0014_add_comprovante_pendente_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatenotificacao",
            name="corpo_whatsapp_interativo",
            field=models.JSONField(
                blank=True,
                help_text='Opcional — substitui "Corpo WhatsApp" em provedores que suportam botões. Schema: {"title": "...", "body": "... %%TAG%%", "footer": "...", "buttons": [{"id": "btn1", "title": "Texto"}, ...]} (máx. 3 botões).',
                null=True,
                verbose_name="WhatsApp Interativo (botões)",
            ),
        ),
    ]
