# Generated by Django 4.2.7 on 2026-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0015_add_corpo_whatsapp_interativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaowhatsapp",
            name="provedor",
            field=models.CharField(
                choices=[
                    ("TWILIO", "Twilio"),
                    ("META", "Meta (WhatsApp Business API)"),
                    ("EVOLUTION", "Evolution API (self-hosted)"),
                    ("ZAPI", "Z-API"),
                    ("BSP", "BSP Brasileiro (Hablla / Poli Digital / Digisac)"),
                ],
                default="TWILIO",
                max_length=50,
                verbose_name="Provedor",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacao",
            index=models.Index(fields=["parcela", "status"], name="notif_parcela_status_idx"),
        ),
    ]
