# Generated by Django 4.2.7 on 2026-04-01 00:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reajuste_desconto_periodo_referencia"),
        ("financeiro", "0003_contrato_reajuste_piso_teto"),
        ("contratos", "0002_prestacaointermediaria_parcela_vinculada"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoReajusteIntermediaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_reajuste",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data do Reajuste"),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="Percentual Aplicado (%)"
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "valor_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Apos Reajuste"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico de Reajuste de Intermediaria",
                "verbose_name_plural": "Historicos de Reajustes de Intermediarias",
                "ordering": ["intermediaria", "-data_reajuste"],
            },
        ),
        migrations.RenameIndex(
            model_name="contrato",
            new_name="contratos_c_numero__654339_idx",
            old_name="contratos_c_numero_idx",
        ),
        migrations.RenameIndex(
            model_name="contrato",
            new_name="contratos_c_status_515d13_idx",
            old_name="contratos_c_status_idx",
        ),
        migrations.RenameIndex(
            model_name="contrato",
            new_name="contratos_c_data_co_856d4d_idx",
            old_name="contratos_c_data_idx",
        ),
        migrations.RenameIndex(
            model_name="indicereajuste",
            new_name="contratos_i_tipo_in_656a47_idx",
            old_name="contratos_i_tipo_in_idx",
        ),
        migrations.RenameIndex(
            model_name="indicereajuste",
            new_name="contratos_i_ano_656d0c_idx",
            old_name="contratos_i_ano_mes_idx",
        ),
        migrations.RenameIndex(
            model_name="prestacaointermediaria",
            new_name="contratos_p_contrat_40d820_idx",
            old_name="contratos_p_mes_idx",
        ),
        migrations.RenameIndex(
            model_name="prestacaointermediaria",
            new_name="contratos_p_paga_a04c2e_idx",
            old_name="contratos_p_paga_idx",
        ),
        migrations.AddField(
            model_name="contrato",
            name="dias_carencia_boleto",
            field=models.IntegerField(
                default=0,
                help_text="Dias sem cobrar multa/juros após vencimento",
                verbose_name="Dias sem Encargos",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="dias_desconto_boleto",
            field=models.IntegerField(
                default=0,
                help_text="Dias antes do vencimento para conceder desconto",
                verbose_name="Dias para Desconto",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="instrucao_boleto_1",
            field=models.CharField(
                blank=True,
                help_text="Primeira linha de instrução do boleto",
                max_length=255,
                verbose_name="Instrução 1",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="instrucao_boleto_2",
            field=models.CharField(
                blank=True,
                help_text="Segunda linha de instrução do boleto",
                max_length=255,
                verbose_name="Instrução 2",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="instrucao_boleto_3",
            field=models.CharField(
                blank=True,
                help_text="Terceira linha de instrução do boleto",
                max_length=255,
                verbose_name="Instrução 3",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="reajuste_piso",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percentual mínimo aplicado ao reajuste (ex: 0 para nunca aplicar deflação)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Piso de Reajuste (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="reajuste_teto",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percentual máximo aplicado ao reajuste (ex: 15 para limitar a 15%)",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Teto de Reajuste (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_valor_desconto",
            field=models.CharField(
                choices=[("PERCENTUAL", "Percentual"), ("VALOR", "Valor Fixo")],
                default="PERCENTUAL",
                max_length=10,
                verbose_name="Tipo de Desconto",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_valor_juros",
            field=models.CharField(
                choices=[("PERCENTUAL", "Percentual"), ("VALOR", "Valor Fixo")],
                default="PERCENTUAL",
                max_length=10,
                verbose_name="Tipo de Juros",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_valor_multa",
            field=models.CharField(
                choices=[("PERCENTUAL", "Percentual"), ("VALOR", "Valor Fixo")],
                default="PERCENTUAL",
                max_length=10,
                verbose_name="Tipo de Multa",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="valor_desconto_boleto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor em percentual ou reais conforme tipo",
                max_digits=10,
                verbose_name="Desconto do Boleto",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="valor_juros_boleto",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Valor em percentual (0,0333 = 1% ao mês) ou reais",
                max_digits=10,
                verbose_name="Juros ao Dia do Boleto",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="valor_multa_boleto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor em percentual ou reais conforme tipo",
                max_digits=10,
                verbose_name="Multa do Boleto",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="bloqueio_boleto_reajuste",
            field=models.BooleanField(
                default=False,
                help_text="Se True, a geração de boletos está bloqueada até aplicar o reajuste",
                verbose_name="Boleto Bloqueado por Reajuste",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="ciclo_reajuste_atual",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número do ciclo de reajuste atual (1 = meses 1-12, 2 = meses 13-24, etc.)",
                verbose_name="Ciclo de Reajuste Atual",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="conta_bancaria_padrao",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta bancária para geração de boletos deste contrato",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos",
                to="core.contabancaria",
                verbose_name="Conta Bancária Padrão",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="data_primeiro_vencimento",
            field=models.DateField(
                help_text="Data de vencimento da primeira parcela",
                verbose_name="Data do Primeiro Vencimento",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="dia_vencimento",
            field=models.PositiveIntegerField(
                help_text="Dia do mês para vencimento das parcelas (1-31)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Dia de Vencimento",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="numero_contrato",
            field=models.CharField(
                help_text="Número único de identificação do contrato",
                max_length=50,
                unique=True,
                verbose_name="Número do Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="observacoes",
            field=models.TextField(
                blank=True,
                help_text="Observações gerais sobre o contrato",
                verbose_name="Observações",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="percentual_juros_mora",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Percentual de juros ao mês sobre o valor em atraso",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Juros de Mora (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="percentual_multa",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Percentual de multa sobre o valor em atraso",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Multa (%)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="prazo_reajuste_meses",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Intervalo em meses para aplicação do reajuste",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Prazo para Reajuste (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="ultimo_mes_boleto_gerado",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número do último mês (relativo ao contrato) com boleto gerado",
                verbose_name="Último Mês com Boleto Gerado",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="usar_config_boleto_imobiliaria",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, usa as configurações de boleto da imobiliária",
                verbose_name="Usar Configurações da Imobiliária",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_entrada",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor pago como entrada (opcional)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor de Entrada",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_financiado",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Valor Total - Valor de Entrada",
                max_digits=12,
                verbose_name="Valor Financiado",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="valor_parcela_original",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Valor inicial de cada parcela (sem reajustes)",
                max_digits=12,
                verbose_name="Valor Original da Parcela",
            ),
        ),
        migrations.AlterField(
            model_name="indicereajuste",
            name="data_importacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o dado foi importado automaticamente",
                null=True,
                verbose_name="Data de Importação",
            ),
        ),
        migrations.AlterField(
            model_name="indicereajuste",
            name="fonte",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fonte dos dados (ex: IBGE, BCB, FGV)",
                max_length=100,
                verbose_name="Fonte",
            ),
        ),
        migrations.AlterField(
            model_name="indicereajuste",
            name="valor_acumulado_12m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Valor acumulado nos últimos 12 meses",
                max_digits=10,
                null=True,
                verbose_name="Acumulado 12 meses (%)",
            ),
        ),
        migrations.AlterField(
            model_name="indicereajuste",
            name="valor_acumulado_ano",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Valor acumulado desde janeiro do ano corrente",
                max_digits=10,
                null=True,
                verbose_name="Acumulado no Ano (%)",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaointermediaria",
            name="mes_vencimento",
            field=models.PositiveIntegerField(
                help_text="Mês relativo ao início do contrato (ex: 6 = sexto mês)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(360),
                ],
                verbose_name="Mês de Vencimento",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaointermediaria",
            name="numero_sequencial",
            field=models.PositiveIntegerField(
                help_text="Número da intermediária (1 a 30)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Número Sequencial",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaointermediaria",
            name="parcela_vinculada",
            field=models.OneToOneField(
                blank=True,
                help_text="Parcela gerada para esta intermediária",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intermediaria_origem",
                to="financeiro.parcela",
                verbose_name="Parcela Vinculada",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaointermediaria",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor da prestação intermediária",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaointermediaria",
            name="valor_reajustado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor após aplicação de reajustes",
                max_digits=12,
                null=True,
                verbose_name="Valor Reajustado",
            ),
        ),
        migrations.AddField(
            model_name="historicoreajusteintermediaria",
            name="intermediaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_reajustes",
                to="contratos.prestacaointermediaria",
                verbose_name="Intermediaria",
            ),
        ),
    ]
