# Generated by Django 4.2.7 on 2026-04-01 01:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0004_reajuste_spread"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="percentual_cessao",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("3.0000"),
                help_text="Percentual cobrado sobre o valor atualizado para cessão de direitos a terceiros",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Taxa de Cessão de Direitos (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="percentual_fruicao",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.5000"),
                help_text="Percentual mensal de fruição em caso de rescisão (uso do imóvel pelo comprador)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Taxa de Fruição (% a.m.)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="percentual_multa_rescisao_adm",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("12.0000"),
                help_text="Percentual de despesas administrativas retido em caso de rescisão",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Despesas Administrativas de Rescisão (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="percentual_multa_rescisao_penal",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("10.0000"),
                help_text="Percentual de cláusula penal retido em caso de rescisão pelo comprador",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Multa Penal de Rescisão (%)",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="tipo_correcao_fallback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IPCA", "IPCA - Índice de Preços ao Consumidor Amplo"),
                    ("IGPM", "IGP-M - Índice Geral de Preços do Mercado"),
                    ("INCC", "INCC - Índice Nacional de Custo da Construção"),
                    ("IGPDI", "IGP-DI - Índice Geral de Preços - Disponibilidade Interna"),
                    ("INPC", "INPC - Índice Nacional de Preços ao Consumidor"),
                    ("TR", "TR - Taxa Referencial"),
                    ("SELIC", "SELIC - Taxa Básica de Juros"),
                    ("FIXO", "Valor Fixo (sem correção)"),
                ],
                help_text="Índice substituto caso o principal seja extinto (ex: INPC se IGPM for extinto)",
                max_length=10,
                verbose_name="Índice de Fallback",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="vendedor_cpf_cnpj",
            field=models.CharField(
                blank=True,
                help_text="CPF ou CNPJ do vendedor pessoa física ou jurídica",
                max_length=18,
                verbose_name="CPF/CNPJ do Vendedor",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="vendedor_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome completo do vendedor (quando diferente da imobiliária)",
                max_length=200,
                verbose_name="Nome do Vendedor",
            ),
        ),
        migrations.CreateModel(
            name="TabelaJurosContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "ciclo_inicio",
                    models.PositiveIntegerField(
                        help_text="Primeiro ciclo de reajuste em que esta taxa se aplica (1 = ano 1)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ciclo Início",
                    ),
                ),
                (
                    "ciclo_fim",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Último ciclo de aplicação. Deixe em branco para "este ciclo em diante"',
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ciclo Fim",
                    ),
                ),
                (
                    "juros_mensal",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Taxa de juros compostos mensais embutida nas parcelas deste ciclo (ex: 0.6000 = 0,60% a.m.)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Juros Mensais (%)",
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Conforme cláusula 8.2 do contrato",
                        max_length=200,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabela_juros",
                        to="contratos.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de Juros por Ciclo",
                "verbose_name_plural": "Tabela de Juros por Ciclo",
                "ordering": ["contrato", "ciclo_inicio"],
                "indexes": [
                    models.Index(
                        fields=["contrato", "ciclo_inicio"], name="contratos_t_contrat_56940a_idx"
                    )
                ],
            },
        ),
    ]
