# Generated by Django 4.2.7 on 2026-04-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0005_contrato_clausulas_vendedor_tabela_juros"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE contratos_contrato DROP COLUMN IF EXISTS vendedor_cpf_cnpj;",
                    reverse_sql="ALTER TABLE contratos_contrato ADD COLUMN IF NOT EXISTS vendedor_cpf_cnpj varchar(18) NOT NULL DEFAULT '';",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="contrato",
                    name="vendedor_cpf_cnpj",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE contratos_contrato DROP COLUMN IF EXISTS vendedor_nome;",
                    reverse_sql="ALTER TABLE contratos_contrato ADD COLUMN IF NOT EXISTS vendedor_nome varchar(200) NOT NULL DEFAULT '';",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="contrato",
                    name="vendedor_nome",
                ),
            ],
        ),
    ]
