# Generated by Django 4.2.7 on 2026-04-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0005_contrato_clausulas_vendedor_tabela_juros"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrato",
            name="vendedor_cpf_cnpj",
        ),
        migrations.RemoveField(
            model_name="contrato",
            name="vendedor_nome",
        ),
    ]
