# Generated by Django 4.2.7 on 2026-04-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0006_remove_vendedor_campos_redundantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="intermediarias_reajustadas",
            field=models.BooleanField(
                default=True,
                help_text="Se marcado, as intermediárias têm o valor atualizado pelo mesmo índice (IPCA etc.) a cada ciclo de reajuste. Se desmarcado, o valor das intermediárias é fixo até o vencimento.",
                verbose_name="Intermediárias Reajustadas pelo Índice",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="intermediarias_reduzem_pmt",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o valor das intermediárias é deduzido do saldo financiado antes de calcular a parcela mensal. Se desmarcado, as intermediárias são amortizações extras sobre a parcela mensal cheia.",
                verbose_name="Intermediárias Reduzem PMT",
            ),
        ),
    ]
