# Generated by Django 4.2.7 on 2026-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0007_contrato_intermediarias_parametros"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="tipo_amortizacao",
            field=models.CharField(
                choices=[
                    ("PRICE", "Tabela Price (PMT constante por ciclo)"),
                    ("SAC", "SAC — Amortização Constante (PMT decrescente)"),
                ],
                default="PRICE",
                help_text="Tabela Price: PMT constante por ciclo, juros decrescentes, amortização crescente. SAC: amortização constante, PMT e juros decrescentes a cada período.",
                max_length=10,
                verbose_name="Sistema de Amortização",
            ),
        ),
    ]
