# Generated by Django 4.2.7 on 2026-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0009_contrato_testemunhas_escritura"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="data_assinatura",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Assinatura"),
        ),
        migrations.AddField(
            model_name="contrato",
            name="documento_assinado",
            field=models.FileField(
                blank=True,
                help_text="Upload do contrato assinado pelas partes (PDF ou imagem)",
                null=True,
                upload_to="contratos/documentos/%Y/",
                verbose_name="Contrato Assinado",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="documento_assinado_content_type",
            field=models.CharField(
                default="application/pdf",
                editable=False,
                max_length=100,
                verbose_name="Content-Type do documento",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="documento_assinado_db",
            field=models.BinaryField(
                blank=True,
                help_text="Cópia do documento em banco de dados — persiste em storage efêmero (Render)",
                null=True,
                verbose_name="Contrato Assinado (banco de dados)",
            ),
        ),
    ]
