# Generated by Django 4.2.7 on 2026-05-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0011_remove_documento_assinado_orphan_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinutaContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "versao",
                    models.CharField(
                        help_text="Ex: v1, v2, 2024-01", max_length=20, verbose_name="Versão"
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Texto completo da minuta ou descrição das alterações desta versão",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Somente a versão ativa é considerada a minuta vigente do contrato",
                        verbose_name="Versão Ativa",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutas",
                        to="contratos.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Minuta de Contrato",
                "verbose_name_plural": "Minutas de Contrato",
                "ordering": ["-criado_em"],
                "unique_together": {("contrato", "versao")},
            },
        ),
    ]
