# Generated by Django 6.0.6 on 2026-07-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0014_contratoimportacao_store_in_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="metodo_cobranca",
            field=models.CharField(
                choices=[
                    ("boleto", "Boleto registrado"),
                    ("carne", "Carnê"),
                    ("bolepix", "Boleto + Pix (BoletoPix)"),
                    ("pix_automatico", "Pix Automático (débito recorrente)"),
                ],
                default="boleto",
                help_text="Forma de cobrança deste contrato (habilitada na imobiliária).",
                max_length=20,
                verbose_name="Método de Cobrança",
            ),
        ),
    ]
