# Generated by Django 6.0.6 on 2026-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0015_contrato_metodo_cobranca"),
        ("core", "0028_alter_parametrosistema_grupo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contrato",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["ATIVO", "SUSPENSO"])),
                fields=("imovel",),
                name="unique_contrato_vigente_por_imovel",
            ),
        ),
    ]
